### ISSUE TITLE
Responsive tables

### ISSUE THREAD

**Issue by hiendv** [hiendv/teible#1]
## Expected Behavior
Responsive tables allow tables to be scrolled horizontally with ease

## Current Behavior
![screenshot from 2018-07-24 15-47-40](https://user-images.githubusercontent.com/1917947/43127142-f0840752-8f58-11e8-8087-2cbebc2444e6.png)

## Possible Solution
- Make `.datatable__wrapper` responsive
- Make `data-table-filter` and `.datatable__text` responsive too

## Context
https://www.facebook.com/groups/vuejsvietnam/permalink/1715705778547050/?comment_id=1722053167912311

**Comment by tucq88** [comment]
This could be an example on stack table row, it's more user-friendly to be honest.
http://johnpolacek.github.io/stacktable.js/

**Comment by hiendv** [comment]
@tucq88 So basically this?

> **Responsive**
Use media queries to toggle the visibility of the original table and the stacktable (check out the stacktable.css example). You can pass in classes or an id to give to the stacktable. Adjust the size of your browser window to see it in action in the example below.

**Comment by tucq88** [comment]
"toggle visibility" seems stupid. But to be honest, I haven't known a better solution yet. May be a pure CSS solution by changing behaviour of row is okay, but its not actual table anymore :(

**Comment by hiendv** [comment]
@tucq88 Yeah, responsive design is a real challenge. I took the initial solution as a best practice from [Bootstrap](https://getbootstrap.com/docs/4.1/content/tables/#responsive-tables). StackColumns or CardTable may sound good to some but seem bad for others. It's kinda controversial. We're building a so-called "simple table component" so let's stick with this ugly bar for a while and see what we can do. :laughing:
