### ISSUE TITLE
Sorting null values throws  error

### ISSUE THREAD

**Issue by ergonomicus** [hiendv/teible#12]
## Expected Behavior
Sorting puts records with null values at the top | bottom

## Current Behavior
Sorting on any column that contains null value raises error " Error in callback for watcher "identifier": "TypeError: Cannot read property 'localeCompare' of null" "

## Possible Solution
Check values before trying to sort

## Steps to Reproduce (for bugs)
Provide items with value of null in some field

## Stack trace
[Vue warn]: Error in callback for watcher "identifier": "TypeError: Cannot read property 'localeCompare' of null"

found in

---> <DataTable> at DataTable.vue
       <CustomersTable> at src/components/CustomersTable.vue
         <Customers> at src/views/Customers.vue
           <App> at src/App.vue
             <Root>

**Comment by hiendv** [comment]
Thank you for reporting. I'm on it.

**Comment by hiendv** [comment]
@ergonomicus Sorry, but which version of vue-teible are you using?

**Comment by hiendv** [comment]
@ergonomicus Fixed in v0.9.5

**Comment by ergonomicus** [comment]
@hiendv In your latest commit you are assuming that all values are strings, but what if we have [-1, 0, 4] etc.
That should be sortable also, right?

**Comment by hiendv** [comment]
@ergonomicus As you can see here, I'm trying to pick a sample element from the array and trying to sort them with the given type. https://github.com/hiendv/teible/blob/46d02b3a9f3779910e627fcbdcaffeea46fcd81a/packages/vue-teible/src/helpers.js#L48-L58

Both numbers and strings are supported. Mixed-type elements will need another approach, I suppose.

**Comment by hiendv** [comment]
I'm having a small problem with node v11 so I will unpublish v0.9.5 for now. v0.9.6 coming soon.

**Comment by ergonomicus** [comment]
OK. Thanks!

**Comment by hiendv** [comment]
Got it. https://github.com/nodejs/node/issues/24294

**Comment by hiendv** [comment]
@ergonomicus v0.9.6 released. Check it out please :D 
https://github.com/hiendv/teible/blob/c760becf75869e54789dddbfa840ba34478e9e53/packages/vue-teible/src/helpers.js#L11-L72

**Comment by ergonomicus** [comment]
@hiendv Yeah, everything seems OK now. Thank you.
