### ISSUE TITLE
Row click event

### ISSUE THREAD

**Issue by AshotN** [hiendv/teible#16]
Is there anyway to know if a user has clicked on a row. Only way I can think of currently is listening for an event on `tbody tr`. But that doesn't feel very clean. Thanks!

**Comment by hiendv** [comment]
@AshotN Hi, could you please describe more about your use-case?
If you are trying to listen for `click` event of a specific row, you can try `slot-scope` like [this](https://github.com/hiendv/teible/blob/master/packages/vue-teible-example/src/Demo.vue#L34-L43). You can try the live demo [here](https://hiendv.github.io/teible/). Clicking `Yo` or `Delete` should result in particular changes.

Thanks a lot for using teible ;)

**Comment by AshotN** [comment]
I wanted to make the entire row clickable. Rather than have a column with a button or checkbox.

**Comment by hiendv** [comment]
@AshotN For now it's not possible because [we don't have any listeners](https://github.com/hiendv/teible/blob/master/packages/vue-teible/src/DataTableBody.vue#L3-L8) in `<tr>`. The workaround is just like you said, we can listen for events on `<tr>`. You can also using `v-ref` for the table to make the listening explicit.
I would happily add the feature if the workaround does not sound good to you.

**Comment by AshotN** [comment]
If it’s not a hassle. I enjoy using teible, but there is a lack of control. If you could add event listeners and the ability to add CSS classes to the table parts. I’d be very content. 

Either way, thanks for the component!

**Comment by hiendv** [comment]
I'm on it :+1: 
Btw, teible using css-modules to customize styling. You can easily write a whole new style or extend stock ones to fit your need. The example below demonstrates 3 ways of styling teible: use built-in themes, use your theme from a sass file, use your theme as an object of mapping
```vue
<script>
import { themeDefault } from 'teible'
import themeFoo from './foo.module.scss'
const themeBar = {
  datatable: 'my_teible',
  datatable__wrapper: 'my_teible__wrapper',
  datatable__screen: 'my_teible__screen',
  datatable__content: 'my_teible__content',
  datatable__row: 'my_teible__row',
  'datatable__row--odd': 'my_teible__row--odd',
  datatable__cell: 'my_teible__cell',
  'datatable__cell--last-column': 'my_teible__cell--last-column',
  'datatable__cell--last-row': 'my_teible__cell--last-row',
  datatable__filter: 'my_teible__filter',
  datatable__input: 'my_teible__input',
  datatable__clear: 'my_teible__clear',
  datatable__x: 'my_teible__x',
  datatable__column: 'my_teible__column',
  'datatable__column--last': 'my_teible__column--last',
  'datatable__column--active': 'my_teible__column--active',
  'datatable__column--sortable': 'my_teible__column--sortable',
  'datatable__column--custom': 'my_teible__column--custom',
  'datatable__column-icon': 'my_teible__column-icon',
  'datatable__column-text': 'my_teible__column-text',
  datatable__pagination: 'my_teible__pagination',
  datatable__plist: 'my_teible__plist',
  datatable__pprevious: 'my_teible__pprevious',
  datatable__pnext: 'my_teible__pnext',
  datatable__plink: 'my_teible__plink',
  datatable__ptext: 'my_teible__ptext',
  'datatable__plink--active': 'my_teible__plink--active'
}
</script>
<style>
.my_teible {}
.my_teible__wrapper {}
// etc
</style>
<template>
  <data-table :theme="themeDefault"/>
  <data-table :theme="themeFoo"/>
  <data-table :theme="themeBar"/>
</template>
```

**Comment by AshotN** [comment]
Thanks for the help. I don’t use Vue much, more of a React guy, so it’s a learning experience.

**Comment by hiendv** [comment]
@AshotN Thanks for your suggestion. I added the feature in [v0.11.2](https://github.com/hiendv/teible/releases/tag/v0.11.2).
The docs is in `vue-teible` [README](https://github.com/hiendv/teible/tree/master/packages/vue-teible).
You can update by reinstall vue-teible with `npm install`.

**Comment by AshotN** [comment]
This made my code a lot cleaner. Thank you so much for the fast response and the help.

**Comment by hiendv** [comment]
It's my pleasure :gift: . Teible's one of my side projects. I just wanted to experiment "writing a Vue library" and it turned out good :rofl: .
If you like my style, you may want to check out [my tab components](https://github.com/hiendv/tabs). It comes with React component too, thanks to a contributor. Although I would be more confident with Vue :rofl:
