### ISSUE TITLE
Refresh Table

### ISSUE THREAD

**Issue by AshotN** [hiendv/teible#17]
If the data is being provided from a function, how would you tell the table to pull the data again?

**Comment by hiendv** [comment]
@AshotN It's possible with `loadItems` method. [README](https://github.com/hiendv/teible/tree/master/packages/vue-teible#methods)
You can use it like this
```vue
<template>
  <datatable ref="foobar">
    ...
  </datatable>
</template>
<script>
export default {
  ...
  methods: {
    reload () {
      this.$refs.foobar.loadItems()
    }
  }
}
</script>

**Comment by AshotN** [comment]
Ah, I must've missed that. Thank you!
