### ISSUE TITLE
Custom styling support

### ISSUE THREAD

**Issue by visualcookie** [hiendv/teible#8]
Is custom styling supported or will it be in the future? I ask since I want to move from `react-table` where I currently struggle with so much to your library. I would especially require to style the Checkboxes for Multi-Select along with the rest.

Maybe something to add to the Roadmap, if not already planned?

**Comment by hiendv** [comment]
Hello @visualcookie, thanks for your attention. And **YES**, custom styling is totally supported.
- For the basic elements, we can override classes with `datatable` prefix.
- Out of your concern, the checkbox is actually a custom column so you will have control for everything. Please see the example at https://github.com/hiendv/teible/blob/master/packages/vue-teible-example/src/Demo.vue#L28-L35

**Comment by hiendv** [comment]
I will try my best to finish and publish the react library in a couple of days. Hope you're satisfied with **teible**!

**Comment by visualcookie** [comment]
Sounds amazing. Sure I am. Always looking for improvements in my code and especially how to implement larger things faster.

Don't rush yourself. Just wanted to check if it's supporting my current use-case. 👍

**Comment by hiendv** [comment]
Glad I could help (in the future). Anw, I will go ahead and close the issue because it's solved. I'll ping you when the React library is ready. Thanks a lot.
